services:
  app:
    build:
      context: .
      args:
        DB_URL: ${DB_URL}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        CLIENT_URL: ${CLIENT_URL}
    env_file: ./.env

    ports:
      - $APP_DOCKER_PORT:$APP_LOCAL_PORT
